-- Edulution admin session access SQL support
-- This file is intended to be used by the backend team to support:
-- 1) admin authentication with email + password
-- 2) fetching all sessions for admin-only access
-- 3) optional center-scoped session retrieval

CREATE TABLE IF NOT EXISTS admins (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  full_name VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL DEFAULT 'admin',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS centers (
  id SERIAL PRIMARY KEY,
  center_name VARCHAR(255) NOT NULL UNIQUE,
  center_code VARCHAR(255) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sessions (
  id UUID PRIMARY KEY,
  center_name VARCHAR(255) NOT NULL,
  center_code VARCHAR(255) NOT NULL,
  class_name VARCHAR(255),
  sessio_date DATE,
  term VARCHAR(50),
  present_learners INTEGER,
  total_in_class INTEGER,
  total_learner_percentage DECIMAL(5,2),
  notes TEXT,
  goals TEXT,
  follow_up TEXT,
  tracking_progress INTEGER,
  tracking_progress_target INTEGER,
  tracking_progress_outcome VARCHAR(50),
  tracking_accuracy INTEGER,
  tracking_accuracy_target INTEGER,
  tracking_accuracy_outcome VARCHAR(50),
  groupings JSONB,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Example admin seed record.
-- Replace the password hash with a real bcrypt/argon2 hash generated by the backend.
INSERT INTO admins (email, password_hash, full_name, role)
VALUES (
  'admin@edulution.org',
  '$2b$10$REPLACE_WITH_BCRYPT_HASH',
  'Edulution Admin',
  'admin'
)
ON CONFLICT (email) DO NOTHING;

-- Admin-only session lookup
SELECT s.*
FROM sessions s
ORDER BY s.sessio_date DESC, s.created_at DESC;

-- Center-scoped session lookup for existing center login flow
SELECT s.*
FROM sessions s
WHERE s.center_name = :center_name
ORDER BY s.sessio_date DESC, s.created_at DESC;

-- Admin authentication query
SELECT id, email, full_name, role
FROM admins
WHERE email = :email;

-- Optional table index to speed up admin queries
CREATE INDEX IF NOT EXISTS idx_sessions_center_name_date
ON sessions (center_name, sessio_date DESC);
